[tasks.pre-clippy]
env = { CARGO_MAKE_CLIPPY_ARGS = "--all-targets --all-features -- -D warnings" }

[tasks.check-style]
dependencies = ["check-format-flow", "clippy-flow"]

[tasks.check-format]
args = ["fmt", "--", "--check"]
